### ISSUE TITLE
Download OIA-MDA8 dataset

### ISSUE THREAD

**Issue by rao1140427950** [nkicsl/OIA-MDA8#1]
I can't find the link to download OIA-MDA8 dataset. Where can I download OIA-MDA8 dataset? Thanks。

**Comment by nkicsl** [comment]
Sorry for that, you can download OIA-ODIR from Baidu Drive now (https://pan.baidu.com/s/1NqRuzAMj4MfStqZ2PSlL1A, PWD:b665).

**Comment by rao1140427950** [comment]
Thank you!

**Comment by nkicsl** [comment]
Thank you for your information.


We have updated the data. Please.


Best,
--
李涛 
博士，教授
南开大学智能计算系统研究室



发件人：Shirjay Rao <notifications@github.com>
发送日期：2019-12-12 12:43:09
收件人：nkicsl/OIA-MDA8 <OIA-MDA8@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[nkicsl/OIA-MDA8] Download OIA-MDA8 dataset (#1)
I can't find the link to download OIA-MDA8 dataset. Where can I download OIA-MDA8 dataset? Thanks。
